resolver: lts-6.11

packages:
- '.'

extra-deps:
- dates-0.2.2.1


# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
