resolver: lts-6.11

packages:
- '.'
- https://hackage.haskell.org/package/dates-0.2.2.1/dates-0.2.2.1.tar.gz

extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
